endpoints:
  - name: Google
    url: https://google.com.sa
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Github
    url: https://github.com/
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Yandex.com
    url: https://yandex.com/
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Bing.com
    url: https://www.bing.com/
    interval: 30s
    conditions:
      - "[STATUS] == 200"


      